CREATE TABLE SUPPORT_TICKET (
    ID BIGINT PRIMARY KEY,
    USER_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    COMMENTS TEXT,
    STATUS VARCHAR(50)
);

CREATE SEQUENCE SUPPORT_TICKET_SEQ
    START WITH 100
    INCREMENT BY 1
